server:
  port: ${PORT:8080}
spring:
  application:
    name: aivleTK

  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username: ${MAIL_USERNAME}
  #    password: ${MAIL_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: "temp@gmail.com"
    password: "temp_password"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


  datasource:
    url: jdbc:mysql://localhost:3306/aivleTK
    username: root
    password: test1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
app:
  cors:
    allowed-origins: "http://localhost:5173, https://calm-tree-0e8ee630f.4.azurestaticapps.net/"

jwt:
  secret:
    key: "aivleaivleaivleaivleaivle1234567aivleaivleaivleaivleaivle1234567"